[package]
name = "reproducible-builds-certification-repository"
version = "0.0.0"

[dependencies]
rocket = "0.3.15"
rocket_codegen = "0.3.15"
rocket_contrib = "0.3.15"
serde = "1.0.71"
serde_derive = "1.0.71"